apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rwm.fullname" . }}
  labels:
    app: {{ template "rwm.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.properties: |-
    debug = false
    server.port = 8080
    spring.security.user.name = {{ .Values.env.username }}
    spring.security.user.password = {{ .Values.env.password }}
    spring.redis.host = localhost
    spring.redis.host.1 = {{ .Values.env.redisHostQA }}
    spring.redis.host.2 = {{ .Values.env.redisHostQA2 }}
    spring.redis.host.3 = {{ .Values.env.redisHostOnline }}
