apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rwm.fullname" . }}
  labels:
    app: {{ template "rwm.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.properties: |-
    spring.application.name = rwm
    server.port = 8080
    spring.security.user.name = {{ .Values.env.username }}
    spring.security.user.password = {{ .Values.env.password }}
    spring.redis.host = {{ .Values.env.redisHost }}
    spring.redis.database = 0
