apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rwm.fullname" . }}
  labels:
    app: {{ template "rwm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "rwm.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: app-vol
          configMap:
            name: {{ template "rwm.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: app-vol
              mountPath: /rwm/config/application.properties
              subPath: application.properties
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
